/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Caja;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC-HOGAR
 */
public class BusquedaFecha extends javax.swing.JFrame {

    //Creamos la conexion a la base de datos
    //Declaramos una coneccion en null al igual que un statement tambien en null
    Connection connection = null;
    Statement statement = null;
    double totalEf, totalMp;
    //Creamos un objeto tabla, un modelo de tabla para trabjar con el, para colocar las consultas en el datatable
    DefaultTableModel modelo = new DefaultTableModel();
    //Creamos el formato para la fecha
    DateFormat f = new SimpleDateFormat("dd/MM/yyyy");
    //Seteamos el patron para el formato de numero 
    String pattern = "#.##";
    //Creamos el formateador para los numeros al cual le pasamos el patron de dos decimales uno por cada # que colocamos
    DecimalFormat decimalFormat = new DecimalFormat(pattern);

    private Connection connect() {
        //Inicializamos la conexion
        Connection conn = null;
        try {
            //Pasamos el nombre de la base de datos a la cual nos vamos a conectar
            conn = DriverManager.getConnection("jdbc:sqlite:dbCaja.db");
        } catch (SQLException e) {
            //Mandamos un mensaje de error a la consola en caso de que aparezca uno
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Error: \n" + e.getMessage() + "\n VUELVA A INTENTARLO");
        }
        //Por ultimo retornamos la conexion
        return conn;
    }

    public BusquedaFecha() {
        initComponents();
        this.setLocationRelativeTo(null);

        // TODO add your handling code here:
        //Aca lo que hacemos es inicializar el modelo de la tabla con los campos que tenemos en la base de datos
        modelo.addColumn("Fecha");
        modelo.addColumn("Ingreso");
        modelo.addColumn("Egreso");
        modelo.addColumn("Observacion");
        modelo.addColumn("Detalle");
        modelo.addColumn("MP");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateFecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalBusqueda = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por Fecha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));
        jPanel1.add(dateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 230, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 524, 230));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOTAL DE LA BUSQUEDA = ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 230, -1));

        totalBusqueda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(totalBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 280, 40));

        jMenu1.setText("Archivo");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Agregar Item");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Imprimir Registros");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton de buscar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date fecha = dateFecha.getDate();
        totalEf = 0;
        totalMp = 0;
        //Creamos un string de 3 columnas el cual va a contener los datos que traeremos de la consulta
        String Dato[] = new String[6];
        //Inicializamos el modelo con cero registros
        modelo.setRowCount(0);

        try {
            //CONECTA A LA BD
            connection = this.connect();
            //Iniciamos el statement de la conexion
            statement = connection.createStatement();
            //Le decimos al statement mediante el metodo setQueryTimeout que si se tarda mas de 20 segundo sin usar entonces se cierra la conexion 
            statement.setQueryTimeout(20);
            //QUERY QUE TRAE TODOS LOS DATOS
            //Ejecutamos el query y guardamos todo lo que nos trae dentro de un ResultSet
            //CICLO QUE LLENA TODO EL MODELO
            //Recorremos los datos que trajo la consulta y de lo asignamos a cada uno de las posiciones correspondientes del array de tipo string de 3 posiciones que llamamos Dato[]
            String query = "SELECT * FROM caja";
            ResultSet rs = statement.executeQuery(query);
            while (rs.next()) {
                if (f.format(Long.parseLong(rs.getString("fecha"))).equals(f.format(fecha))) {
                    //Convertimos la fecha de time stamp a fecha con formato dado arriba, usamos la conversion de string a long por que es un dato demaciado largo par que sea integer
                    Dato[0] = f.format(Long.parseLong(rs.getString("fecha")));
                    //VAlidamos si el campo ingreso o egreso viene null segun sea el caso guardamos cero en el que venga null 
                    if (rs.getString("ingreso") == null) {
                        Dato[1] = "0";
                        Dato[2] = rs.getString("egreso");
                    } else if (rs.getString("egreso") == null) {
                        Dato[1] = rs.getString("ingreso");
                        Dato[2] = "0";
                    }
                    Dato[3] = rs.getString("observacion");
                    Dato[4] = rs.getString("detalle");
                    Dato[5] = String.valueOf(rs.getInt("mp"));
                    //Agregamos la informacion al modelo de la tabla para mostrarlo en pantalla
                    modelo.addRow(Dato);

                    //Realizamos validacion para realizar la suma o resta y asi sacar el total de los valores de la caja teniendo en cuenta ingreso y egreso
                    if (rs.getString("ingreso") == null) {
                        if (rs.getInt("mp") == 1){
                            totalMp = totalMp - Double.parseDouble(rs.getString("egreso"));
                        }else {
                            totalEf = totalEf - Double.parseDouble(rs.getString("egreso"));
                        }
                    } else if (rs.getString("egreso") == null) {
                        if (rs.getInt("mp") == 1){
                            totalMp = totalMp + Double.parseDouble(rs.getString("ingreso"));
                        }else {
                            totalEf = totalEf + Double.parseDouble(rs.getString("ingreso"));
                        }
                    }

                    totalBusqueda.setText("MP $" + String.valueOf(decimalFormat.format(totalMp) + " Ef $" + String.valueOf(decimalFormat.format(totalEf))));
                }
            }

            //LLENAMOS LA TABLA CON EL MODELO
            jTable1.setModel(modelo);
            //OCULTAMOS EL ID EN LA TABLA
            //tabla.getColumn("id").setMaxWidth(50);
        } catch (SQLException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Error en la buscqueda: \n" + e.getMessage() + "\n VUELVA A INTENTARLO");
        } finally {
            //Al finalizar cerramos la conexion
            try {
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                // connection close failed. en el caso de que haya un error en la conexion
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error: \n" + e.getMessage() + "\n VUELVA A INTENTARLO");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //Agregar Item
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Caja caja = new Caja();
        caja.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //Salir
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    //Imprimir registros
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        //Creamos el documento a llenar
        Document documento = new Document();
        float totalIngreso = 0;
        float totalEgreso = 0;
        //Creamos la tabla para la informacion que lenaremos dentro del documento
        PdfPTable tabla = new PdfPTable(6);

        try {

            //Acedemos a la ruta del pdf que vamos a guardar para esto hacemos uso de el metodo get property de la clase system con la cual mediante user.home accedemos a la raiz es decir si ponemos cmd vemos que la ruta es c:/user/ale y alli esta todo ahi podemos hacceder a cualquier parate de la pc ya que es el directorio raiz de nuestra computadora
            String ruta = System.getProperty("user.home");
            //Ahora escribimos el pdf mediante pdf writer, para esto usamos el metodo get instance de la clase pdfwriter, y alli colocamos donde vamos a escribirlo, es decir que le pasamos el documento primero el que creamos arriba y seguidamente le pasamos la ruta donde lo vamos a guardar
            //Con la instancia de fieloutputstream le vamos a poder indicar donde vamosa  escribir el pdf es decir la ruta especifica, es edcir que le pasamos la ruta y le concatenamos el lugar especifico donde estara
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/CajaDia.pdf"));
            //Ahora abrimos el documento para poder empezar a escribir dentro del mismo 
            documento.open();

            //Seguido empezamos a crear la tabla            
            tabla.addCell("Fecha");
            tabla.addCell("Detalle");
            tabla.addCell("Ingresos");
            tabla.addCell("Egresos");
            tabla.addCell("Observacion");
            tabla.addCell("MP");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }

        //Recorremos el jtable para cada elemento del mismo lo vallamos agregando a la tabla que se ensertara dentro del pdf
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            tabla.addCell((String) jTable1.getValueAt(i, 0));
            tabla.addCell((String) jTable1.getValueAt(i, 4));
            tabla.addCell((String) decimalFormat.format(Float.parseFloat((String) jTable1.getValueAt(i, 1))));
            tabla.addCell((String) decimalFormat.format(Float.parseFloat((String) jTable1.getValueAt(i, 2))));
            tabla.addCell((String) jTable1.getValueAt(i, 3));
            tabla.addCell((String) jTable1.getValueAt(i, 5));
            //Por cada vuelta vamos sumando cada uno de los valores tanto de ingreso como egreso para sacar los totales
            totalIngreso = totalIngreso + Float.parseFloat(jTable1.getValueAt(i, 1).toString());
            totalEgreso = totalEgreso + Float.parseFloat(jTable1.getValueAt(i, 2).toString());
        }

        //Creamos un parrafo
        Paragraph paragraph_1 = new Paragraph();
        //Agregamos la informacion a mostrar en ese parrafo, con decimal format le sacamos los decimales de mas al numero y como estamos concatenando con un string entonces no hace falta convertir a string si no que se convierte automaticamente
        paragraph_1.add("TOTAL INGRESOS = $" + decimalFormat.format(totalIngreso));
        //Alineamos la informacion a la izquierda dentro del documento
        paragraph_1.setAlignment(Paragraph.ALIGN_LEFT);

        Paragraph paragraph_2 = new Paragraph();
        paragraph_2.add("TOTAL EGRESOS = $" + decimalFormat.format(totalEgreso));
        paragraph_2.setAlignment(Paragraph.ALIGN_LEFT);

        Paragraph paragraph_3 = new Paragraph();
        paragraph_3.add("TOTAL GENERAL Mercado Pago = $" + decimalFormat.format(totalMp));
        paragraph_3.setAlignment(Paragraph.ALIGN_LEFT);
        
        Paragraph paragraph_4 = new Paragraph();
        paragraph_3.add("\nTOTAL GENERAL Efectivo = $" + decimalFormat.format(totalEf));
        paragraph_3.setAlignment(Paragraph.ALIGN_LEFT);
        
        Paragraph paragraph_5 = new Paragraph();
        paragraph_3.add("\nTOTAL GENERAL = $" + decimalFormat.format(totalEf + totalMp));
        paragraph_3.setAlignment(Paragraph.ALIGN_LEFT);

        try {
            //Luego dentro de un ty catch, agregamos en el orden que queremos que se vea dentro del docuemnto cada uno de los elementos
            //Para el caso de querer agregar fraces directamente usamos una instancia de la clase Phrase pasandole el string que queremos postrar en uno le pasamos la fecha y en otros un salto de linea para separar la informacion dentro del documento
            documento.add(new Phrase("Caja dia: " + jTable1.getValueAt(1, 0)));
            documento.add(new Phrase(" \n "));
            documento.add(tabla);
            documento.add(new Phrase(" \n "));
            documento.add(paragraph_1);
            documento.add(paragraph_2);
            documento.add(paragraph_3);
            documento.add(paragraph_4);
            documento.add(paragraph_5);
            JOptionPane.showMessageDialog(null, "PDF generado en escritorio");
        } catch (DocumentException ex) {
            Logger.getLogger(BusquedaFecha.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Al finalizar cerramos el documento
        documento.close();

        //Enviamos a la pantalla principal y cerramos la actual
        Caja cj = new Caja();
        cj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaFecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel totalBusqueda;
    // End of variables declaration//GEN-END:variables
}
